# Generated by Django 5.2 on 2025-05-12 18:59

import django.db.models.deletion
import loja.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='foto',
            field=models.ImageField(upload_to=loja.models.RenameImage('categoria/')),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoriaid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loja.categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(upload_to=loja.models.RenameImage('produtos/')),
        ),
    ]
